models/Comment.php
<?php

/**
 * This is the model class for the comments.
 *
 * The followings are the available columns in table '{{posts_comments}}':
 * @property integer $id ID of the comment
 * @property integer $post_id ID of the post the comment belongs to
 * @property integer $user_id ID of the user who wrote the comment (if logged in)
 * @property string $name Name of the user (if not logged in)
 * @property string $email Email of the user (if not logged in)
 * @property string $website Website of the user (if not logged in)
 * @property string $content Content of the comment
 * @property string $created Date of creation
 * @property integer $parent_id ID of the parent comment
 * @property boolean $approved Whether the comment is approved
 *
 * @package CMS
 * @subpackage Comment
 */
class Comment extends CActiveRecord
{
	/**
	 * Returns the static model of the specified AR class.
	 *
	 * @param string $className active record class name.
	 *
	 * @access public
	 * @return Comment the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * Get the model table name.
	 *
	 * @access public
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return '{{cms_comment}}';
	}

	/**
	 * Get the attribute validaton rules.
	 *
	 * @access public
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		return array(
			array('post_id, content, created', 'required'),
			array('user_id', 'required', 'on' => 'registered'),
			array('name, email', 'required', 'on' => 'guest'),
			
			array('user_id, post_id, parent_id', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max' => 75),
			array('email', 'length', 'max' => 100),
			array('website', 'length', 'max' => 100),
			
			array('approved', 'boolean'),
			array('website', 'url'),

			array('user_id', 'unsafe'),
			array('id, post_id, content', 'safe'),
			array('name, email, website', 'safe', 'on' => 'guest'),
		);
	}

	/**
	 * Get the comment relations.
	 *
	 * @access public
	 * @return array relational rules.
	 */
	public function relations()
	{
		return array(
			'thePost' => array(self::BELONGS_TO, 'Post', 'post_id'),
			'theUser' => array(self::BELONGS_TO, 'User', 'user_id'),
			'theParent' => array(self::BELONGS_TO, 'Comment', 'parent_id'),
		);
	}
	
	/**
	 * Get the comment default scope.
	 *
	 * @access public
	 * @return array
	 */
	public function defaultScope() {
		$t = $this->getTableAlias(false, false);
		
		if (Yii::app()->user->isBoard()) {
			return array(
				'order' => "$t.created DESC",
			);
		}
		else {
			return array(
				'condition' => "$t.approved = :approved",
				'order' => "$t.created DESC",
				'params' => array(
					':approved' => true,
				),
			);
		}
	}
	
	/**
	 * Get the comment scopes.
	 *
	 * @access public
	 * @return array
	 */
	public function scopes() {
		$t = $this->getTableAlias();
		
		return array(
			'approved' => array(
				'condition' => "$t.approved = :approved",
				'params' => array(
					':approved' => true,
				),
			),
		);
	}
	
	/**
	 * Get the HTML content for this comment.
	 *
	 * @access public
	 * @return string
	 */
	public function getHtmlContent() {
		return nl2br($this->content);
	}

	/**
	 * Create empty comment for given post.
	 *
	 * @access public
	 * @return Comment
	 */
	public static function createForPost(Cms $post)
	{
		if (!Yii::app()->user->isGuest) {
			$comment = new Comment('registered');
		}
		else {
			$comment = new Comment('guest');
		}

		$comment->post_id = $post->id;
		return $comment;
	}

	/**
	 * Get the attribute labels.
	 *
	 * @access public
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => Yii::t('Comment', 'ID'),
			'post_id' => Yii::t('Comment', 'Artikel'),
			'user_id' => Yii::t('Comment', 'Benutzer'),
			'name' => Yii::t('Comment', 'Name'),
			'email' => Yii::t('Comment', 'E-Mail'),
			'website' => Yii::t('Comment', 'Internetseite'),
			'content' => Yii::t('Comment', 'Inhalt'),
			'created' => Yii::t('Comment', 'Erstellt'),
			'parent_id' => Yii::t('Comment', 'Übergeordnet'),
			'approved' => Yii::t('Comment', 'Genehmigt'),
		);
	}
	
	/**
	 * Before validate method. Set approved status for the comment.
	 *
	 * @access public
	 * @return boolean
	 */
	public function beforeValidate() {
		if (parent::beforeValidate() and $this->isNewRecord) {
			$this->created = date('Y-m-d H:i:s');
			
			if (!Yii::app()->user->isGuest) {
				$this->user_id = Yii::app()->user->id;
				$this->approved = true;
			}
			else {
				$comment = Comment::model()->findByAttributes(
					array(
						'email' => $this->email,
						'approved' => true,
					)
				);
				
				if (!is_null($comment))
					$this->approved = true;
				else
					$this->approved = false;
				
				if (strpos($this->website, 'http://') === false)
					$this->website = 'http://' . $this->website;
			}
		}
		
		return parent::beforeValidate();
	}
}

controllers/CommentController.php
<?php

/**
 * Comment controller.
 *
 * @package CMS
 * @subpackage Comment
 */
class CommentController extends Controller
{
	/**
	 * Default action.
	 *
	 * @access public
	 * @var string
	 */
	public $defaultAction = 'admin';

	/**
	 * Default layout.
	 *
	 * @access public
	 * @var string
	 */
	public $layout = '//layouts/admin';
	
	/**
	 * Get the controller filters.
	 *
	 * @access public
	 * @return array
	 */
	public function filters()
	{
		return array(
			'accessControl',
		);
	}
	
	/**
	 * Get the access rules.
	 *
	 * @access public
	 * @return array
	 */
	public function accessRules()
	{
		return array(
			array('allow',
				'actions'=>array('admin', 'delete', 'approve'),
				'roles' => array(User::LEVEL_BOARD),
			),
			array('deny',
				'users'=>array('*'),
			),
		);
	}
		
	/**
	 * Manage not approved comments.
	 *
	 * @access public
	 * @return void
	 */
	public function actionAdmin()
	{
		$dataProvider = new CActiveDataProvider(
			'Comment', 
			array(
				'criteria' => array(
					'condition' => 'approved = :approved',
					'params' => array(
						'approved' => false,
					),
				),
			)
		);
		
		$this->render(
			'/comment/admin', 
			array(
				'dataProvider' => $dataProvider,
			)
		);
	}
	
	/**
	 * Delete comment.
	 *
	 * @param integer $id Comment ID
	 *
	 * @access public
	 * @return void
	 */
	public function actionDelete($id) {
		if (Yii::app()->request->isPostRequest) {
			$model = Comment::model()->findByPk($id)->delete();

			if(!isset($_GET['ajax'])) {
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
			}
		} else {
			throw new CHttpException(400);
		}
	}
	
	/**
	 * Approve comment.
	 *
	 * @param integer $id Comment ID
	 *
	 * @access public
	 * @return void
	 */
	public function actionApprove($id) {
		$model = Comment::model()->findByPk($id);
		
		if (!$model->approved) {
			$model->approved = true;
			if ($model->save()) {
				Yii::app()->user->setFlash('info', Yii::t('Comment', 'Kommentar genehmigt.'));
			}
			else
				throw new CHttpException(500);
		}
		else {
			Yii::app()->user->setFlash('warning', Yii::t('Comment', 'Kommentar wurde schon genehmigt!'));
		}
		
		$this->redirect(array('/cms/comment/admin'));
	}
}

views/comment/_form.php
<h3><?php echo Yii::t('Comment', 'Kommentar schreiben'); ?></h3>

<?php
$form = $this->beginWidget(
	'EBootstrapActiveForm', 
	array(
		'id' => 'comment-form',
		'horizontal' => true,
	)
);
?>

	<?php if (Yii::app()->user->isGuest): ?>

		<?php echo $form->bootstrapTextField($model, 'name'); ?>

		<?php echo $form->bootstrapTextField($model, 'email'); ?>
		
		<?php echo $form->bootstrapTextField($model, 'website'); ?>

	<?php else: ?>
		
		<p><?php echo Yii::t('Comment', 'Du schreibst als <em>{user}</em>', array('{user}' => Yii::app()->user->name)); ?></p>

	<?php endif; ?>

	<?php echo $form->bootstrapTextArea($model, 'content'); ?>

	<?php echo $form->beginActions(); ?>
		<?php echo EBootstrap::submitButton($model->isNewRecord ? Yii::t('Comment', 'Kommentar schreiben') : Yii::t('Comment', 'Speichern'), 'success'); ?>
	<?php echo $form->endActions(); ?>

<?php $this->endWidget(); ?>

views/comment/_view.php
<div class="comment-entry" id="comment-<?php echo $data->id; ?>">

	<h3>
	<?php if (isset($data->theUser)): ?>
		<?php echo EBootstrap::link($data->theUser->name, array('/user/user/view', 'id' => $data->theUser->id)); ?>
	<?php else: ?>
		<?php echo (empty($data->website)) ? EBootstrap::encode($data->name) : EBootstrap::link($data->name, $data->website); ?>
	<?php endif; ?>
		<small><?php echo strftime('%e. %B %G %H:%M', strtotime($data->created)); ?></small>
	</h3>

	<div class="comment-content">
		<?php echo $data->htmlContent; ?>
	</div>
	
</div>

views/comment/admin.php
<?php

$this->title[] = Yii::t('Comment', 'Kommentare');
$this->title[] = Yii::t('Core', 'Administration');

$this->breadcrumbs = array(
	Yii::t('Blog', 'Artikel') => $this->createUrl('/cms/blog/admin'),
	Yii::t('Comment', 'Kommentare'),
);

$this->beginWidget(
	'AdminWidget', 
	array(
		'title' => Yii::t('Comment', 'Kommentare (offen)'),
		'buttons' => EBootstrap::buttonGroup(
			array(
				//EBootstrap::ibutton()
			)
		),
		'icon' => 'comment',
		'table' => true,
	)
);

$this->widget(
	'EBootstrapGridView', 
		array(
		'id' => 'comment-grid',
		'dataProvider' => $dataProvider,
		'columns' => array(
			'id',
			array(
				'name' => 'user_id',
				'type' => 'raw',
				'value' => '(isset($data->theUser)) ? EBootstrap::link($data->theUser->username, array("/user/user/view", "id" => $data->theUser->id)) : EBootstrap::encode($data->name)',
			),
			array(
				'name' => 'post_id',
				'type' => 'raw',
				'value' => 'EBootstrap::link($data->thePost->title, array("/cms/blog/viewTitle", "title" => $data->thePost->slug))',
			),
			array(
				'name' => 'created',
				'value' => 'date("d.m.Y H:i:s", strtotime($data->created))',
				'filter' => false,
			),
			array(
				'class' => 'EBootstrapButtonColumn',
				'template' => '{view}{delete}{approve}',
				'viewButtonUrl' => 'Yii::app()->createUrl("/cms/blog/viewTitle", array("title" => $data->thePost->slug, "#" => "comment-".$data->id))',
				'buttons' => array(
					'approve' => array(
						'imageUrl' => false,
						'url' => 'Yii::app()->createUrl("/cms/comment/approve", array("id" => $data->id))',
						'label' => '<i class="icon icon-ok"></i>'
					),
				),
			),
		),
		'pager' => array(
			'class' => 'EBootstrapLinkPager',
			'header' => false,
		),
		'pagerAlign' => 'right',
	)
); 

$this->endWidget();